Uie
jina-ai/jina-paddle-hackathon pull request #4
Opened 2023-03-11 07:31 UTC by SOVLOOKUP

2023-03-28 04:39 UTC, numb3r3 requested changes

2023-03-28 04:39 UTC, numb3r3 commented on .vscode/settings.json
> +{
ignore `.vscode` in the git repo

2023-03-28 04:39 UTC, numb3r3 commented on README.md
> +2. [src/plato-mini](./src/plato-mini/) Jina 的 Plato-Mini Executor & Flow 实现、功能测试
It seems that the second item is not relevant to this ticket.

2023-03-28 04:39 UTC, numb3r3 commented on src/uie/.pdm.toml
> +[python]
ignore the local pdm toml file.

2023-03-28 04:39 UTC, numb3r3 commented on src/uie/README.md
> +please install pdm first: `pip install pdm`
Please provide more information about `pdm`.

2023-03-28 04:39 UTC, numb3r3 commented on src/uie/pdm.lock
> +# This file is @generated by PDM.
ignore this file as well

2023-03-28 04:39 UTC, numb3r3 commented on src/uie/src/uie_executor/config.yml
> +  keywords: ['nlp']
refine the keywords by providing more relevant tags.

2023-03-28 04:39 UTC, numb3r3 commented on src/uie/src/uie_executor/executor.py
> +        super().__init__(**kwargs)
The default `schema` can be passed as a parameter.

2023-03-28 04:39 UTC, numb3r3 commented on src/uie/src/uie_executor/executor.py
> +            d.text = str(self.uie(d.text))
Should we have a structured response? For example, to return the result in `.tags`:
```
result_doc.tags['时间'] = ...
result_doc.tags['选手'] = ...
...
```

2023-03-30 14:54 UTC, SOVLOOKUP commented
Thanks for your advice!

2023-05-10 02:43 UTC, numb3r3 approved these changes
LGTM

2023-05-11 05:58 UTC, merged